GSA-TTS/identity-handbook

_articles/appdev-deploy.md

See commits for what's actually new in this PR

Move over AppDev deploy guide, update it

---

_articles/project-principles.md
_data/highlight_categories.yml
_includes/articles_category.md

- Also update index page to support custom order in categories

Import project principles to public handbook

---

_articles/appdev-cloud-gov-deploy.md

I wrote down instructions I saved from @solipet in this article

Add instructions for how to deploy OIDC, SAML sinatra example apps

---

_articles/sprint-ceremonies.md

This article only covers individual scrum team ceremonies. I plan to follow up with an update to add ceremonies that span teams.

Add an article describing scrum team ceremonies

---

_articles/offboarding.md

For things like Details out of Login.gov
Corresponding login-devops PR: https://github.com/18F/identity-devops/pull/2858

Add partial offboarding instructions

---

_articles/offboarding.md
_articles/onboarding.md

Update JIRA user instructions

---

_articles/appdev-deploy.md
_articles/bug-bounty-triage.md
_articles/deploying-sp-to-prod.md
_articles/saml.md

Made a few touch-ups and moved some emails into the Google Docs appendix

Migrate more articles from private handbook

---

_articles/biannual-review.md

Here is the PR removing from the private handbook: https://github.com/18F/identity-handbook-private/pull/164

Move review document to new handbook

---

_articles/onboarding.md

Adds review of the Design System for all new team members
Adds email signature
Replaces login with login.gov, where appropriate
Uses proper capitalization of login.gov, where appropriate

Updates onboarding doc

---

_articles/troubleshooting-quick-reference.md

Paul's new page he showed off at the Eng huddle

Link to Wiki page on troubleshooting

---

_articles/appdev-deploy.md
_articles/appdev-oncall-guide.md
_articles/slack.md

Update login-product Slack channel references to login-appdev

---

_articles/appdev-lambda-jobs.md
_articles/appdev-secrets-configuration.md

- Also page on how to update secrets in S3 since that was missing

Add first pass at AWS Lambda background job documentation (LG-3676)

---

_articles/infrastructure-aws-accounts-and-roles.md

Fix a broken link to identity-devops Wiki

New name for IAM private doc

---

_articles/offboarding.md
_articles/onboarding.md
_articles/slack.md

- Added links to authentication and identity proofing intro videos
- Added more Slack groups and onboarding reminders

Onboarding updates

---

_articles/accounts.md
_articles/offboarding.md

Please take a look at the appendix page too!

List accounts that we use, link to appendix page for access (LG-3817)

---

_articles/accounts.md
_articles/appdev-deploy.md
_articles/appdev-lambda-jobs.md
_articles/incident-response-checklist.md
_articles/infrastructure-acceptance-criteria.md
_articles/infrastructure-ceremonies.md
_articles/infrastructure-iam-configs.md
_articles/infrastructure-oncall-guide.md
_articles/offboarding.md
_articles/onboarding.md

Based on feedback in: https://github.com/18F/identity-handbook/pull/51#discussion_r539677290

Use link helper for articles

---

_articles/definition-of-ready.md

**Why**: Action item from recent postmortem.

Update Definition of Ready to include user impact for bugs

---

_articles/cost-recoverability.md
_articles/project-principles.md

Pull cost recovery into a separate article

---

_articles/cost-recoverability.md
_articles/project-principles.md

New people can be confused by cost recoverability and a goal to be cost neutral.
This seemed like a good place to add into the handbook.  Feedback v. welcome.

Add a note about cost recovery and cost-neutral goal

---

_articles/openssl-recipes.md

Based on https://github.com/18F/identity-pki/pull/190 and https://github.com/18F/identity-pki/pull/189

Add OpenSSL pkcs7 conversion commands

---

_articles/troubleshooting-pivcacs.md

Instructions to match new helpers added in https://github.com/18F/identity-pki/pull/195

Update PIV/CAC debugging guide with new helpers

---

_articles/incident-response-checklist.md
_articles/secops-incident-response-guide.md

The correct template name is "incidents.md"

Fix incident template URLs

---

_articles/appdev-deploy.md

Removed the instructions to deploy to staging. Staging is updated daily to the `master` branch (both idp and pki)

We no longer manually deploy to Staging

---

_articles/appdev-updating-maxmind-db.md

Let's record this so that future us can remember what the heck we did
All the sensitive stuff is in the appendix

Record instructions for updating MaxMind GeoIP

---

_articles/onboarding.md

- Notes for VPN and Admin access
- Instructions for feds-only and contractors-only Google Groups
- Add security overview from Summit.

Add collected onboarding updates

---

_articles/partnerships-raci.md

This is a high-level summary of the data that the partnerships team put together here: https://docs.google.com/spreadsheets/d/1GV9FOdXtbY4cmMupPMMz0nrhTgTWMVZkzWPXO18bEZw/edit#gid=0
This page is pretty long, and consists of multiple tables. Putting everything into one table does not work well horizontally.
Does this seem OK, or is there a better way?

Add high-level Partnerships RACI data

---

_articles/infrastructure-email.md

Provides a public friendly overview of email flow in and out of
login.gov.

Add first draft of email overview

---

_articles/annual-certificate-rotation.md

Copied from the private handbook

Migrate SAML cert rotation article

---

_articles/appdev-deploy.md

Per discussion from yesterday's Engineering Huddle

Update deploy doc with updated release naming process

---

_articles/sprint-teams.md

Looking for feedback on 
a. the summaries of the people
b. the descriptions of what the sprint teams actually do

Add Sprint Teams page

---

_articles/appdev-deploy.md

Some updates based on our conversation at eng huddle yesterday

Update deploy docs about kinds of deploys, schedules, who does them

---

_articles/appdev-ruby-worker-jobs.md

Adds details based on questions from @mzia

Add additional details to Ruby Workers architecture

---

_articles/annual-certificate-rotation.md

The file is in Google Drive - please take a look and let me know if you have any feedback!

Add link to SAML rotation comms plan

---

_articles/incident-response-checklist.md
_articles/secops-incident-response-guide.md

* Simplifies IR Checklist
* Extends IR Guide to include FAQ/Expectations

Incident Response updates

---

_articles/infrastructure-auto-tf-runbook.md

`app_sandboxes.yml` makes it easy!

Add note about adding personal sandbox to auto-tf

---

_articles/team-roles.md

Moved content from [internal brainstorm/GDoc](https://docs.google.com/document/d/1TeFipYWDQJm5lw91F-I17nPZXt2xueoRLiakFYHwlLs/edit#)

Add Team Roles page

---

_articles/sprint-teams.md

@pauldoomgov does this seem like an OK description? :)

add team Radia to teams page

---

_articles/identity-proofing-testing.md

The extra description is for searchability/SEO

Link out to developer documentation for testing notes

---

_articles/appdev-deploy.md

This is happening often enough.... may as well document the steps

Update deploy docs to describe resolving merge conflicts

---

_articles/partnerships-ticket-handling.md

[LG-4544] Add article about handling partner support tickets

---

_articles/github.md

See https://github.com/18F/identity-idp/pull/5142

Deprecrate identity-proofer-gem too

---

_articles/definition-of-done.md

Remove reference to slim files

---

_articles/onboarding.md

This comes from feedback during our weekly staffing meeting.

Add check-in schedule to onboarding steps

---

_articles/glossary.md

Earlier today, I was like "what the heck is an [iaa_gtc](https://github.com/18F/identity-idp/blob/main/app/models/agreements/iaa_gtc.rb)??" so now I'm making an article so somebody else could maybe look up the same thing in the future

Add a glossary page

---

_articles/glossary.md

Add IDV definition to glossary

---

_articles/appdev-cloud-gov-deploy.md

- Also use interpolation to minimize typo risk

Update list of deployed sample apps

---

_articles/help-center-contact-form.md

I saw we have another one of these tickets coming up, so figured it was worth documenting and making sure we link to the instructions

Add article for adding items to contact form dropdown

---

_articles/glossary.md

Merged with https://github.com/18F/identity-idp/wiki/Glossary

Merged with our old glossary

---

_articles/onboarding.md

Thanks @LeighFinkel for pointing this out :)

Fix spelling mistake

---

_articles/appdev-proofing-ruby-worker-jobs.md

Update permission name for proofing workers

---

_articles/leave-guidance.md

Add leave guidance

---

_articles/leave-guidance.md

Be more specific about back-ups

Update leave page

---

_articles/gitlab.md
_articles/infrastructure-scaling.md

Document GitLab/Login.gov auth integration

---

_articles/secops-incident-response-guide.md
_articles/vendor-outage-response-process.md

Documents the process for configuring the idp when a vendor has an outage. Linked from the incident response guide.

LG-5184: new process for a vendor outage

---

_articles/sprint-teams.md

Updating that Team Katherine now works on the IdP too.
Background context: I will be onboarding a new TK member, so I thought that this should be updated.

Update Team Katherine's description

---

_articles/troubleshooting-pivcacs.md

To include instructions on using https://github.com/18F/identity-pki/pull/259/files

update pivcac troubleshooting page

---

_articles/infrastructure-tips.md

Added notes about S3 bucket names and DNS zones.

Add more detail to AWS resource table

---

_articles/appdev-deploy.md
_articles/daily-deploy-schedule.md

- And a table of what time it really is locally because time zones
are really hard

Add an article with the daily deploy schedule

---

_articles/daily-deploy-schedule.md

| --- | --- |
| <img width="623" alt="Screen Shot 2021-12-29 at 12 07 21 PM" src="https://user-images.githubusercontent.com/458784/147699623-28c0b0e4-f234-4e7d-87e2-b7ee28b6a568.png"> |  <img width="623" alt="Screen Shot 2021-12-29 at 12 07 07 PM" src="https://user-images.githubusercontent.com/458784/147699631-8bb405c9-0c37-486e-a6a6-ddafee376803.png"> |

Update table to remove some visual noise

---

_articles/incident-response-checklist.md
_articles/secops-incident-response-guide.md

Puts a lot on the Comms Lead shoulders, intentionally.
The other roles should be focused on coordination, technical
resolution, and maintaining a timeline.

Clarify some IR duties and align checklist and guide

---

_articles/appdev-lambda-jobs.md
_articles/appdev-proofing-ruby-worker-jobs.md
_articles/appdev-risc-ruby-worker-jobs.md
_articles/appdev-static-assets-cdn.md
_articles/definition-of-done.md
_articles/idp-artifact-building-architecture.md
_articles/reporting-dashboard-architecture.md

**Why**: So it's easier to see the image at a bigger size

Make links to diagrams clickable

---

_articles/orgchart.md

Just a link to a private GSheet.

Add Login.gov Org Chart page

---

_articles/help-center-contact-form.md

Update contact form updating instructions

---

_articles/sprint-teams.md

Update sprint teams page, and update focus areas

---

_articles/analytics-events.md
assets/js/analytics-events.js

- Updated event example
- Link to legacy event names documentation
- Update sidenav to include specific events

Update Analytics Events documentation

---

_articles/incident-response-checklist.md
_articles/secops-incident-response-guide.md

As discussed in the Incident Review for the recent proofing outage,
the "everyone in" IR expectation is probably not useful at our current
size.  Instead the SL is expected to asses the situation and call in
additional help as needed.

Refine incident response expectations

---

_articles/appdev-deploy.md

Just a few minor revisions based on my recent deploy experience.
- Fix link to NewRelic prod errors page
- Add note about scale-in delay
- Link to list of GitHub admins

Improve deploy documentation

---

_articles/incident-response-checklist.md
_articles/secops-incident-response-guide.md

Adds a few strategic links to private incident response runbooks.

Mention incident response runbooks

---

assets/js/setup.tsx

https://github.com/18F/identity-handbook/pull/235#discussion_r833614998

Fix import to be a type import

---

_articles/team.md
_layouts/default.html
assets/js/analytics-events.tsx
assets/js/github.tsx
assets/js/private-articles.tsx
assets/js/team.tsx
private.md

- Leverage useQuery and createPortal

Redo team page components

---

_articles/incident-response-checklist.md
_articles/secops-incident-response-guide.md

Refines Scribe role description.   Explicitly removes expectation
of a full transcript.

Better descibe Scribe role

---

_articles/sprint-teams.md

New sprint team name, new entry in the handbook

Add team Kimberly

---

_articles/sprint-teams.md

A new entry in the handbook for the new sprint team.
I also alphabetized the entries and made some small formatting changes.

Add team Joy

---

_articles/github.md

Missing a few repos that are commonly used.

Add Platform repos

---

_articles/platform-auto-tf-runbook.md

**Autoterraform Pausing CLI Instructions**
This PR adds instructions related to the new autoterraform pausing utility. 
Addresses #3985
</details>

Autoterraform Pausing CLI Instructions

---

_articles/definition-of-done.md

As discussed with team on 5/09.

First stab at special PR instructions for changes impacing billing/costs

---

_articles/slack.md

New thing means new documentation!

Add devtools oncall Slack handle

---

_articles/platform-oncall-guide.md

Members of Radia or Mary may be in the rota.   Also adds a note on the new boundary time.

Minor updates to Platform On-Call

---

_articles/sprint-teams.md

PR to add Team Agnes to the Sprint Teams page

Add Team Agnes - Attempts API

---

_data/sprint_teams.yml

- Added Team Ross to the sprint teams yml file
- Updated gems that were preventing local testing

Add Team Ross to Sprint Teams list

---

_articles/partnerships-provision-test-users.md
_articles/partnerships-test-ssns.md

[LG-7002] Add page on adding test SSNs for partners in the sandbox

---

_articles/onboarding.md

Some slight streamlining for onboarding new users into AWS and GitLab

Refine onboarding notes

---

_articles/github.md
_articles/pull-request-review.md

My action item from Eng Huddle this week

Add article about pull request conventions

---

_articles/appdev-deploy.md

**Why**: Since it no longer exists

Remove references to idpxtra from deploy guide

---

_articles/appdev-secrets-configuration.md

**Why**:
Improve clarity on...
- Where do the default values come from
- How are they overridden
- The ability to override values in local development

Improve clarity on application configuration

---

_articles/troubleshooting-pivcacs.md

Related to https://github.com/18F/identity-pki/pull/315

Fix and update instructions for troubleshooting PIV/CAC

---

admin/config.yml

I am looking to create a temporary sandbox section for NetlifyCMS demos. If there is a better place to put these, please let me know.

create temporary netlify sandbox section

---

_articles/deploying-sp-to-prod.md
_articles/partnerships-config-pr-checklist.md
_articles/partnerships-reporting-doc.md
_articles/partnerships-ticket-handling.md

Replaced Smartsheet URL with Zendesk, added new Partner Success Engineer workflow document.

Edits to partnerships section of handbook

---

_articles/platform-alerting.md

This is my guess at answering @aduth 's [question in slack](https://gsa-tts.slack.com/archives/CR6BF3CQK/p1662490664609689)

Fix broken link

---

_articles/glossary.md

I basically took @juliaelman 's [words in Slack](https://gsa-tts.slack.com/archives/C23LEJLMC/p1663074784722819?thread_ts=1663073774.132319&cid=C23LEJLMC) and formatted them as sections in this glossary

Differentiate between Identity Verification and Identity Proofing

---

_articles/appdev-secrets-configuration.md

(my action item from today's eng huddle)
I already updated [devops wiki page](https://github.com/18F/identity-devops/wiki/Common-Infrastructure-Commands-and-Shortcuts#app-s3-secret) to point to the exisitng page

Update documentation on app-s3-secret

---

_articles/partnerships-pilot-playbook.md

Adding this to our list of resources.

Add the Pilot Playbook

---

_articles/incident-response-checklist.md

A few things noted in today's Wargames

Minor updates to IR checklist

---

admin/config.yml

I need to add the editorial workflow for the demo I am doing today. Trying to get this to match the brochure site.

Add editorial workflow

---

_articles/device-identification.md

Add information about testing and configuration device identification / fraud detection.

Add link to Device Profiling document

---

_articles/device-identification.md
_articles/device-profiling.md

I had meant to include this commit on #338, but I think my firewall blocked my push. Anyway, this just switches around terminology to say "Device profiling" instead of "device identification"

Device identification -> device profiling

---

_articles/example-netlify-demo.md

Creating a demo page to show while demo for CMS. This is so that there is no risk in deploying to the live site.

Create Article “example-netlify-demo”

---

_articles/devops-scripts.md
_articles/github.md
_articles/piv-ssh.md
_articles/postmortem-template.md
_articles/pull-request-review.md
_articles/template.md
_articles/troubleshooting-quick-reference.md
_categories/appdev.md

- Add subcategories to Development articles
- Add commented out subcategory to template article
- Add description to AppDev category

Small organizational changes

---

_articles/platform-gitlab.md

Adding some items that are handy when things are busted.

Add some more meat to the GitLab docs

---

_articles/devops-scripts.md

Does this strike the right balance of salesmanship and fear?   Not sure.  There are more SSM documents defined but not listed here due to their use by wrappers.

Add a few notes on ssm-command and listing available SSM documents

---

_articles/appdev-deploy.md

This PR updates the amount of time to wait when starting to monitor migrations

Add information about time before monitoring migrations

---

_articles/devops-scripts.md

Adds new scary warning, [slack context](https://gsa-tts.slack.com/archives/C0NGESUN5/p1672877169007879?thread_ts=1672876394.671029&cid=C0NGESUN5)
| screenshot |
| --- |
| <img width="501" alt="Screen Shot 2023-01-04 at 4 23 29 PM" src="https://user-images.githubusercontent.com/458784/210674599-5de65912-1d83-431e-b69e-3a450084c17f.png"> |

Add warning about passenger-restart script

---

_articles/platform-gitlab-prod-deploy.md

Add gitlab prod deploy process documentation

---

_articles/appdev-oncall-guide.md

This is temporary until we can push partners to use our RISC API to self-report these

Add oncall instructions for password reset

---

_articles/secops-incident-response-guide.md

Updated to link to current (FY22) incident response plan

IRP Link Update

---

_articles/incident-response-checklist.md

A follow on to #365 to get the IRR v2 link into the IR Checklist.

Update link to the V2 IR guide in the IR checklist

---

_articles/glossary.md

Based on a conversation with Carrie

Add 3PAO to glossary (and also FedRAMP)

---

_articles/incident-response-checklist.md

A few adjustments to help the Comms role

Add a few IR checklist refinements

---

_articles/wargames-dungeon-masters-guide.md

This starts a page to help DMs, which is timely as we are about to have a lot more of them.

Add Wargames DM's Guide

---

_articles/wargames-dungeon-masters-guide.md

Removes some typos and grammatical mistakes.
Adds a section on supporting a positive learning environment.

A few DM guide spelling fixes and a section on the room environment

---

_articles/glossary.md
_articles/sbar-template.md
cspell.json

To help me (and maybe others) find this in the future

Add link to SBAR template from handbook

---

_articles/platform-gitlab.md

Also add a missing line so that the cert will be proper.

update gitlab docs to use 2023 saml

---

_articles/platform-gitlab-imagesigning.md

added docs on gitlab image signing

---

_articles/product-artifacts.md

@zachmargolis - I wanted to offer some suggestions on how we clarify _when_ to use a 1-pager versus an SBAR. What do you think of these general recommendations? 
cc @carriemcgrath @2hsieh since y'all have also talked with me about some of these ideas

clarify 1-pager vs SBAR

---

_articles/openssl-recipes.md

Inspired by https://github.com/18F/identity-saml-sinatra/pull/123

Update OpenSSL recipes with SHA-1 fingerprint recipe

---

_articles/openssl-recipes.md

I only partially fixed the bug caught by https://github.com/18F/identity-handbook/pull/412#discussion_r1165741780

Fix markdown link syntax

---

_articles/eng-design-doc.md
_articles/product-artifacts.md
_includes/article_url.txt

It was amateur hour for me this week, clearly
| ---- | --- |
|  <img width="642" alt="Screen Shot 2023-04-13 at 4 07 24 PM" src="https://user-images.githubusercontent.com/458784/231901890-ff0169f8-4536-4eb8-a7df-9589ac1d91bb.png"> | <img width="642" alt="Screen Shot 2023-04-13 at 4 07 19 PM" src="https://user-images.githubusercontent.com/458784/231901884-c5499a40-b22f-4844-aa9c-41cb71c4f281.png"> |

Fix broken markdown link

---

_articles/accounts.md
_articles/appdev-oncall-guide.md
_articles/incident-response-checklist.md
_articles/platform-oncall-guide.md
_articles/platform-splunk-oncall.md
_articles/secops-incident-response-guide.md

Preparing to move from OpsGenie to Splunk On-Call.

Add Splunk On-Call information

---

_data/sprint_teams.yml

Unsure how it got broken! But this works now

Update Team Agnes README link

---

_articles/partnership-kudos-doc.md

Jira Ticket: 
Relevant Slack convo: https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1664482997966809
Created a kudos document in the partnerships handbook to document past kudos. Document is currently empty at the moment as they need to be pulled from Slack and emails.

Added partnerships kudos doc

---

_articles/biannual-review.md

Removing line about contractors to align with conversations at the leadership level.

Update language about 360s

---

_data/sprint_teams.yml

Update Team Agnes focus

---

_articles/deploying-sp-to-prod.md

Add instructions on how to get into rails console and make things a bit clearer.

update manual recycle instructions

---

_articles/appdev-deploy.md
_articles/deploying-sp-to-prod.md

use ALL option with scale-remove-*-instances scripts (vs. separate idp / worker calls)

---

_articles/partnership-feedback-form.md
_articles/partnership-kudos-doc.md

Previously the page had a google doc as a placeholder and is now being swapped with a google sheet with partner feedback/kudos.
Waiting for confirmation from AM team.

Added partner feedback/kudos g-sheets

---

_articles/devops-scripts.md

Document data-pull profile-summary subtask

---

_articles/glossary.md

References:
- https://about.usps.com/postal-bulletin/2020/pb22556/html/cover_004.htm
- https://www.uspsoig.gov/reports/audit-reports/retail-systems-software-deployment-and-functionality

Add glossary terms related to in-person proofing with USPS

---

_articles/sprint-teams.md
_data/sprint_teams.yml

Change Notes:
- Added Team Timnit to the sprint teams page
Screenshots

Add Team Timnit to the sprint teams page

---

_articles/reporting-process.md

Been getting this question the last few days, wanted to write it down and then share it down in Slack

Add note about which requests are handled by Team Agnes/Ursula

---

_articles/devops-scripts.md

Document action-account script which includes subtasks.
- suspend-user
- reinstate-user
- review-reject
- review-pass

Document action-account script

---

_articles/incident-response-checklist.md

Per a recent incident that happened outside of normal businesses hours, this step was missed

Add note that Comms Lead should be paged if outside of business hours

---

_articles/vendor-outage-response-process.md

This is a follow-on from LG-8870

 LG-9664 - Updated page about vendor outage flags to reflect recent changes.

---

_articles/appdev-deploy.md

Followup to #455, saw @zachmargolis's suggestion after merging.

Deploy instructions: Also look at asg-size before deploying

---

_articles/appdev-deploy.md

`#login-product-strategy` renamed to `#login-delivery`

Update the deploy guide to reflect a channel name change

---

_articles/devops-scripts.md

Document data-pull uuid-export subtask

---

_articles/appdev-deploy.md

We have a new workflow to announce deployments, so we should tell people how to use it

Add IdP workflow instructions

---

_articles/devops-scripts.md
_articles/troubleshooting-pivcacs.md

Documentation for:
- `bin/oncall/download-piv-certs`
- `bin/oncall/otp-deliveries`

Add documentation for new bin/oncall scripts

---

_data/sprint_teams.yml

This updates to the new on-call Slack handle for Team Joy.

Update Joy On-Call Handle

---

_articles/devops-scripts.md

Removed as of https://github.com/18F/identity-devops/pull/6715

Remove reference to uuid-lookup SSM document (LG-10895)

---

_articles/devops-scripts.md

- Add data-pull events-summary task
- Add query-cloudwatch --date option

Update scripts documentation

---

_articles/monthly-key-metrics-explainer.md

Next steps: a PR in the IDP to link to this document

Adds an explanation doc for the Monthly Key Metrics report

---

_articles/monthly-key-metrics-explainer.md

Got a request to move this somewhere private

Move Monthly Key Metrics explainer to Google Docs

---

_articles/secops-incident-response-guide.md

Aligning Scribe responsibilities across the IR guide and IR checklist

Update Scribe role to include creating incident review doc

---

_articles/appdev-testing-credentials.md

[Drafted in GDocs here](https://docs.google.com/document/d/1fyR0kqKHNstO39SLCg3K1erAzxcIhC7mJYJ4kE5XI-Q/edit)

Add best practices doc for using API credentials

---

_articles/appdev-deploy.md

Update the Slack channel to make ♻️ announcements from #identity-idp to #login-appdev

update channel to login-appdev

---

_articles/github.md

Addresses https://github.com/18F/identity-handbook/pull/488#discussion_r1412479275

Fix typo in GitHub access section

---

_articles/gpo-designated-receiver.md

- Ask folks to sign up directly or ask #login-team-ada for questions
- Describe how to update the PII in config

Update GPO designated receiver information

---

_articles/wargames-players-guide.md
package-lock.json

This change adds a wargames player's guide. This includes:
- A tech lead preparation list
(Ideally, we could build out other prep lists for other roles, and other helpful information that may relieve anxiety in volunteering for a new role.)

Add wargames player page

---

_articles/incident-response-checklist.md

During wargames, I noticed a typo in messenger documentation.  I am submitting this PR to fix it.

Fix typo in incident response checklist

---

_articles/devops-scripts.md

[it's been fixed](https://gsa-tts.slack.com/archives/C16RSBG49/p1700257489075339) for at least a few months now

Remove note about VPN requirement, it's been fixed for zscaler

---

_articles/platform-gitlab-prod-deploy.md

Updated:
- Removed deprecated auto_tf
- Updated to talk about checking background migrations
- Misc improvements

updated documentation about gitlab deploys

---

_articles/platform-deploy-devops-code.md

Fix link on Devops page

---

_articles/product-demo-recordings.md

add product demo recordings suggestion

---

_articles/appdev-deploy.md

This PR adds a line on how to get `.rc-changelog.md` file

Add troubleshooting note to get changelog notes manually

---

_data/sprint_teams.yml

[LG-13016](https://cm-jira.usa.gov/browse/LG-13016)
Adds team Annie to sprint_teams.yml

LG-13016: Add sprint team Annie

---

_articles/saml.md

• Update markup so that links are anchor tags in page HTML
• Fix spacing to make the text more readable

link/pretty print saml.md

---

_articles/logs-schema.md
cspell.json

PR for adding logs schema as per the current design of the data warehouse [here](https://www.figma.com/board/dVajb29rIkUzAQCBQRShe6/Rails-Column-Extraction-Background-Job?node-id=0-1&t=GEdcBHyxx80ErdN9-1)

Added logs schema with a note for data warehouse

---

_articles/platform-gitlab-imagesigning.md
cspell.json

 Update image signing page to reference terraformed kms key

---

_articles/appdev-acuant-sdk-test-plan.md
cspell.json

The article describes the process for manually testing the Acuant SDK prior to each idp deploy.

LG-13793: New article for smoke testing the Acuant SDK

---

_articles/appdev-deploy.md

Feedback from running through the deploy process with Eileen

Add more explicit "gh" command line tool setup

---

_articles/manage-50-50-state.md

Add instructions for replicating columns in DMS

---

_articles/definition-of-ready.md

Add mention of stack traces or logs for Bug tickets

---

_data/sprint_teams.yml

Added team Melba's slack group name `@login-melba`

Update sprint_teams.yml with Melba group name

---

_articles/devops-scripts.md

Add note about sharing diffs to appdev

---

_articles/reporting-process.md

In-repo copy of Stacey's branch: https://github.com/GSA-TTS/identity-handbook/pull/604

Update reporting process to reflect new SOP

---

_data/sprint_teams.yml

Redo of @StaceyLEvans 's https://github.com/GSA-TTS/identity-handbook/pull/608, but from the main repo.
Also adds a commit to remove "product: true" because that comes with an Oncall Rotation requirement

Add team Evelyn

---

_articles/deploying-sp-to-prod.md

This adds the specific query for the rails console to search for Service Provider by issuer
Also removed the word 'run' in front of the commands and the period so its easier to copy and paste
https://gsa-tts.slack.com/archives/C04RGFTFD70/p1727962461115269?thread_ts=1727903963.600769&cid=C04RGFTFD70

Update deploying-sp-to-prod.md with console query

---

_articles/appdev-oncall-guide.md

This content moved to Gitlab, and this is the updated link.

Update IG requests link

---

_articles/devops-scripts.md

Update the "Scripts" page with information about how to output event data from `query-cloudwatch` to a SQLite database.

Document query-cloudwatch --sqlite option

---

_articles/appdev-feature-flags.md

Based on discussion [here](https://gsa-tts.slack.com/archives/C03KDV9S8T1/p1720015058170999), there's quite a bit of ambiguity in environments and their interaction with different elements of configuration. This PR tries to disambiguate some, definitely open to suggestions.

Try to clarify production section of configuration, deployed environments and prod

---

_articles/appdev-deploy.md

This PR takes the place of #588.

Document risks of no-migration recycles

---

_articles/manage-50-50-state.md

Inspired by this [github conversation](https://github.com/18F/identity-idp/pull/11440#discussion_r1825976279), I added another scenario to our 50/50 state documentation.
I haven't experienced this 50/50 state scenario with any of my previous PRs.  As a result, I'd appreciate input from anyone who has previously witnessed this scenario during a deploy.  Thanks! 🙏🏻

Add new scenario to 50/50 docs

---

_articles/appdev-oncall-guide.md

Move from the internal document to Handbook.
Rearranged some sections and eliminated duplication.

Add Rotation Logistics

---

_articles/sandboxes-and-staging-environments.md

Update link to point to internal handbook

---

_articles/appdev-i18n.md

- Update content to include Chinese (Simplified) as an available language Login.gov currently supports
- Updated link text and link to point at [Content Translation Process SOP](https://docs.google.com/document/d/16MacAb1WKiQJJ634Cpjg8WkziiyMJMopA07rUpHP2Vs/edit?tab=t.0#heading=h.l6bljy4rjlyu) rather than deprecated [Login.gov Translation Process](https://docs.google.com/document/d/1-wNXxyvxrsUeHkMOfhBpoSTCTZULOXNlCkBdNxiLa3c/edit?tab=t.0#heading=h.w0c3f0nrg6gp)  
1. Start server, inspect page for content updates
2. Ensure updated link works
| - | - |
| ![Screenshot 2024-12-11 at 8 09 03 AM](https://github.com/user-attachments/assets/39d02655-fdb8-48fd-a92e-903e24fe57cf) | ![Screenshot 2024-12-11 at 8 08 41 AM](https://github.com/user-attachments/assets/7a408882-78ac-497 …

Update translation process article

---

package-lock.json
package.json

Updates the Login.gov Design System (`@18f/identity-design-system`) dependency to the latest version, from 9.0.0 to 9.4.0.
Release notes: https://github.com/18F/identity-design-system/releases
1. Verify site builds and is navigable, without visual regressions
Most noticeable effect here will be the new alert styling, present on the homepage.
Before|After
---|---

Update Login.gov Design System to latest version

---

_articles/appdev-deploy.md

This PR makes a first round of improvements in the deployment article.
Provide a checklist of steps to confirm the changes.

Make first pass of changes in deployment doc

---

_articles/annual-certificate-rotation.md
_articles/appdev-acuant-sdk-test-plan.md
_articles/appdev-deploy.md
_articles/appdev-proofing-ruby-worker-jobs.md
_articles/appdev-risc-ruby-worker-jobs.md
_articles/appdev-secrets-configuration.md
_articles/appdev-troubleshooting-production.md
_articles/appdev-troubleshooting-sandbox.md
_articles/cloudwatch-101.md
_articles/daily-deploy-schedule.md
_articles/deploying-sp-to-prod.md
_articles/devops-scripts.md
_articles/github-gitlab.md
_articles/google-analytics.md
_articles/idp-artifact-building-architecture.md
_articles/manage-50-50-state.md
_articles/offboarding.md
_articles/partnerships-ticket-handling.md
_articles/platform-gitlab-env-deploy.md
_articles/platform-gitlab-prod-deploy.md
_articles/platform-gitlab.md
_articles/product-gitlab-roadmapping.md
_articles/reporting-dashboard-architecture.md
_articles/saml.md
_articles/slack.md
_articles/wargames-players-guide.md
_articles/windows-virtual-machine.md
cspell.json
package.json

Updates spell checker to consider common misspellings of words, including a suggested alternative.
**Draft:**
Verify build passes, and that revised content changes look sensible.

Flag and suggest alternatives for common mispellings

---

_articles/appdev-troubleshooting-production.md

Document commonly used logs

---

_articles/team-roles.md

Fixes [LG-15801](https://cm-jira.usa.gov/browse/LG-15801)

Update Wording on Team Roles Page based on Executive Order 14151

---

_articles/cost-recoverability.md

These links are out of date as new guidance has been issued since this was written. This PR updates the links and associated content.

Fix links and description of funding directives
