GSA-TTS/identity-handbook

- _articles/contributing.md
- _articles/offboarding.md
- _articles/onboarding.md
Taking another swing without shaving the Yak.
- Added onboarding and offboarding docs
- Removed google group addresses
Corresponding Private Handbook PR: https://github.com/18F/identity-handbook-private/pull/149
> Add onboarding and offboarding docs

- _articles/onboarding.md
- spec/html_spec.rb
- spec/spec_helper.rb
- spec/support/matchers.rb
- As we migrate we link in to the old handbook. This adds a spec that
will fail if we continue to link to the old article after already
migrating it
> Make sure we link to articles in the public handbook

- spec/support/matchers.rb
The repos page links to the private handbook's URL to show what site it goes to, and links to the root.
The "private handbook lint" script makes sure that if we link to the old handbook, the corresponding page should not exist.
However, we kind of need to have a root page, so that's a special case, so I updated the matcher to skip that
> Fix private handbook matcher to allow links to root

- _articles/appdev-troubleshooting-production.md
- _articles/troubleshooting-pivcacs.md
migrates article from the private wiki: https://github.com/18F/identity-private/wiki/Operations:-Troubleshoot-certificate-invalid-errors-with-PIV-CAC
> Add PIV/CAC debugging guide for adding missing certs (LG-3523)

- Gemfile
- Gemfile.lock
- _config.yml
- _layouts/default.html
- federalist.json
- Takes advantage of new federalist config to do full clone
cc @davemcorwin
Example:
> Show last modified date (from git) on handbook pages

- _articles/deploying-sp-to-prod.md
- _articles/onboarding.md
This PR should replace Aaron's partnerships-specific onboarding doc (https://docs.google.com/document/d/1ip6oEA7sQjuNUbIrDvO11c1iDxapUyRkXE6SpGdOEak/edit#)
There were only a couple things in your list that weren't already in the public handbook.
When this looks :+1: to you we'll make a deprecation note in your GDoc and add a link to the handbook article: https://handbook.login.gov/articles/onboarding.html
This also begs the question if the linked "partnerships area" in the old, private handbook is still useful.
Aaron, should we move that document over also?
> Add Partnerships specific onboarding tasks

- _articles/definition-of-done.md
"Database indexes exist for any new queries" was not formatted as a list item, and would appear as combined with the previous list entry
Before|After
---|---
> Fix list formatting for engineering definition of done

- _articles/incident-response-checklist.md
- _articles/secops-incident-response-guide.md
Adds an Incident Reponse Checklist to act as both a companion to our Security
Incident Reponse guide and an extension with helpful tips.
> Add IR checklist

- _articles/incident-response-checklist.md
- Remove `- [ ]` checkboxes, they don't render well, aren't interactive
- Clean up link formatting
- Expand acronyms
- Move to "Development" section of handbook (from Team)
> Clean up formatting of incident response checklist

- _articles/saml.md
Replaced instructions on how to hack around the encrypted response with a note about the new option to skip encryption.
> Note on skipping encryption

- _articles/saml.md
Somehow the `dev` env was configured with the same cert signature as in `int`, so we were getting an Invalid Signature error in the SAML Sinatra sample app in `dev`. This walks through what I had to do to resolve it.
> guidance on how to fix Invalid Signature

- _articles/appdev-oncall-guide.md
This is an update to include internal on-call guidance specified in a Google Doc.
Please feel free to comment on this PR, and also to leave comments in the linked GDoc.
Another link to the GDoc: https://docs.google.com/document/d/1mOU3rnBJUKiMNFnz-odudmzNCo06CoKsAlCX1ZrK4ZY/edit#
> Add link to internal on-call guidance

- _articles/appdev-i18n.md
- _articles/saml.md
This pull request updates the translation guidance for secure.login.gov and login.gov. It helps to make translations easier and more accurate for everyone on the team to be able to make translations if they need to.
> Adding updated guidance for the translation process

- _articles/infrastructure-email.md
Wrap up initial email docs with a link to the private runbook
> Add link to private Email runbook

- _articles/appdev-deploy.md
**Why**: If one is to assume the set of commands are for a revert branch yet to be created, omitting the flag would result in an error "error: pathspec 'revert-rc-123' did not match any file(s) known to git".
> Add new-branch flag for rollback instructions

- _articles/appdev-oncall-guide.md
I searched this page for the link to the IG request guide and it was a small "here" link which made it hard for me to find.
These changes to headings will add items to the table of contents that should hopefully make things easier to find too
> Update AppDev oncall to make it easier to find IG requests guide

- _layouts/article.html
Yay for USWDS
| Before | After |
| --- | ---- | 
| <img width="304" alt="Screen Shot 2021-02-16 at 9 29 41 AM" src="https://user-images.githubusercontent.com/458784/108099648-c118b200-7039-11eb-9076-0da67b988d29.png"> | <img width="304" alt="Screen Shot 2021-02-16 at 9 29 59 AM" src="https://user-images.githubusercontent.com/458784/108099661-c4ac3900-7039-11eb-9e33-96948309a08d.png"> |
> Fix table of contents rendering on smaller viewports

- _articles/infrastructure-acceptance-criteria.md
- _articles/infrastructure-ceremonies.md
- _articles/infrastructure-oncall-guide.md
As discussed in 2021-02-20 Team Radia Retro: We are removing
the Pending Acceptance column on our board and changing procedure as
follows:
* Engineers working an issue must provide evidence showing the
requested value is being provided
* Once evidence is documented, engineers can move issues directly
to Done without waiting on a Pending Acceptance step
> Remove Pending Acceptance and AC Club

- _articles/annual-certificate-rotation.md
Clarifies the blocker for deployment of updated Chef code before the new SAML certificate is actually ready for use.
> Add note on waiting for devops deploy before updating SAML config

- _articles/windows-virtual-machine.md
Related: https://github.com/18F/identity-idp/pull/4708#discussion_r582140342
**Why**:
- So content isn't duplicated between the handbook and IDP README, and instead exists as up-to-date in a single canonical location
- To apply guidance for all applications, not just IDP (e.g. sample apps)
**Live Preview:** https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.app.cloud.gov/preview/18f/identity-handbook/aduth-vm-idp-config/articles/windows-virtual-machine.html
> Update Virtual Machine guidance to link to IDP-specific instructions

- _articles/openssl-recipes.md
I hope that in 3 years these just work so nobody has to blindly futz with OpenSSL
> Add OpenSSL recipes for converting pfx (pkcs12) to PEM

- _articles/appdev-lambda-jobs.md
- _includes/articles_category.md
- _layouts/article.html
- assets/css/main.scss
I don't know what our approach is for old articles, I figured this one was kind of useful as a reference so I opted to deprecated it rather than direct delete? I know we linked to it from some previous SCR docs
So I created a new concept of deprecating an article which adds:
| item | screenshot |
| --- | --- |
| grayed out link and deprecation note on homepage | <img width="485" alt="Screen Shot 2021-04-22 at 9 27 43 AM" src="https://user-images.githubusercontent.com/458784/115750907-83901800-a34d-11eb-9d96-6b28e9644a6c.png"> |
| deprecated title on article page | <img width="701" alt="Screen Shot 2021-04-22 at 9 27 35 AM" src="https://user-images.githubusercontent.com/458784/115750919-8559db80-a34d-11eb-972f-f2e2c1708f97.png"> |
> Deprecate lambda jobs article

- .circleci/config.yml
- _config.yml
**Why**: Jekyll and CircleCI configurations assume a Yarn lockfile which doesn't exist. It (as well as a package-lock.json) had existed prior to #2. There should be only one. Since there's already an NPM lockfile, use it for caching, and exclude from Jekyll build.
> Update configuration to use NPM instead of Yarn

- .circleci/config.yml
**Why**: There is no deployment as part of CircleCI. This happens in Federalist. This was a remnant from the old private version of the handbook, which included a deployment step.
> Rename build workflow to omit "deploy" mention

- _articles/appdev-deploy.md
- Add `aws-vault` prefix to every command so it's less error-prone to copy-paste individual lines
- Add more rollback instructions
- Add notes for `--skip-migration` for recycle deploys
> Update deploy docs

- _articles/appdev-oncall-guide.md
- _articles/incident-response-checklist.md
https://github.com/18F/identity-devops/wiki/On-Call-Guide-Quick-Reference#emergency-contacts exists and should probably be linked in a few spots.
> Pepper the Emergency Contact List a few places

- _articles/appdev-lambda-jobs.md
- _articles/appdev-smoketest-debugging.md
- _articles/deploying-sp-to-prod.md
- _articles/incident-response-checklist.md
- _articles/secops-incident-response-guide.md
- _articles/windows-virtual-machine.md
- _includes/alert.html
**Main Change**: Highlighting the note from the long incident response checklist as a block
**Other Changes**:
- Factor out a partial for alerts
- Small cleanups to the short incident checklist
- Move the secops (full guide) into its own category so it's easier to find the short checklist at the top of the page
> Add notes to incident guide

- _articles/appdev-ruby-worker-jobs.md
So when we're ready to go to prod, we have something easy to reference
> Add instructions for how to enable ruby workers in an env

- _articles/github.md
Could also get the `proofer-gem` proactively? 🤷
> Mark repos as deprecated/archived now

- _articles/appdev-ruby-worker-jobs.md
**Why**: So that the expiration behavior is clearly defined.
See Slack thread: https://gsa-tts.slack.com/archives/C01D7MWNE64/p1623333374015500
> Workers: Clarify presigned URL expiration behavior

- _articles/appdev-deploy.md
New worker type means new command to copy-paste
> Add worker host type to deploy guide

- _layouts/default.html
- search.json
We were missing a `desc` attribute in `search.json` so it wasn't being interpolated as a title attribute correctly
| --- | --- |
| <img width="359" alt="Screen Shot 2021-07-08 at 4 08 59 PM" src="https://user-images.githubusercontent.com/458784/125001246-0d738700-e007-11eb-95ec-48a7a99f5368.png">  | <img width="359" alt="Screen Shot 2021-07-08 at 4 08 10 PM" src="https://user-images.githubusercontent.com/458784/125001250-0ea4b400-e007-11eb-9df4-a51a3795d074.png"> |
> Fix search

- _articles/appdev-deploy.md
**Why**: Because, unfortunately, the live proofing flow is not covered by automated testing
> Add instructions to the deploy manager guide to test proofing in staging

- _articles/glossary.md
Follow-up to #144 
- Use abbreviations, acronyms as headers (shorter links)
- Update intro
- Fix some formatting
> Clean up glossary merge

- _articles/sandboxes-and-staging-environments.md
**Why**: So that we can have a reference for which environments exist and the differences between them.
Redirects to an internal Google Doc.
> Add environments stub page

- _articles/slack.md
First, I'd like to get consensus on some naming conventions for our channels.  After we seem :+1: I will embark on a journey to rename channels that do not comply.
[Here is a GSheet with an export of our public channels.](https://docs.google.com/spreadsheets/d/1EmV8arSvs0HARB95rTUGVgUtiAdGYzvQcZbrItmrrV4/edit?ts=60eca39a#gid=0)
Can you think of any more naming conventions we should have?
> Slack channel naming conventions

- _articles/appdev-troubleshooting-production.md
**Why**: Because `production-power` isn't a valid profile name.
>aws-vault: error: exec: Error getting temporary credentials: profile production-power: credentials missing
> Fix typo in aws-vault command

- _articles/reporting-dashboard-architecture.md
**Why**: Because it's inaccurate, and likely a copy-paste error from similar [Background Jobs article / image](https://handbook.login.gov/articles/appdev-proofing-ruby-worker-jobs.html).
See also: https://github.com/18F/identity-handbook/pull/158#discussion_r697110515
> Update reporting dashboard image caption

- _plugins/content_typography.rb
**Why**: So that links are styled using the design system, instead of browser defaults.
An alternative can be to configure [the `$theme-global-link-styles` SASS variable](https://github.com/uswds/uswds/blob/019eda3109a9074923e60326a4aadb4c6b56d04a/src/stylesheets/global/_typography.scss#L17-L19). However, this applies to all links in the layout, which may have unexpected repercussions. Instead, extending Kramdown ensures that styles are only applied to parsed Markdown content.
Before|After
---|---
Kramdown monkey-patching reference: https://github.com/gettalong/kramdown/blob/0b0a9e0/lib/kramdown/parser/kramdown/link.rb#L37-L51
> Add design system link styling

- _articles/incident-response-checklist.md
- _articles/secops-incident-response-guide.md
> Add links to GSA IR email template and Incident Review copy doc

- _articles/onboarding.md
- Remove team-specific guidance, point to new GDocs instead
- Better calendar-adding instructions
- Fix Slack link
> Onboarding Updates

- _articles/slack.md
**Why**: It appears to not exist anymore. login-appdev-team is the user group for application development team, and is already mentioned further down in the list.
> Remove login-eng from Slack team groups

- _articles/vendor-outage-response-process.md
**Why:** Since it is now possible to configure messaging to be shown in these flows in the case of an SMS or voice outage (Pinpoint).
> LG-5185: Add SMS and Voice to vendor outage response process

- _articles/queries.md
- Adds a new "total accounts created" (slightly different from "fully registered IAL 1")
- Adds forms of queries that can be used to approximate historical values (account deletes may mess with all of those, which is why they are not exact)
> Update user queries

- _articles/slack.md
Listing `@login-grace` and `@login-katherine` under [Team Handles](https://handbook.login.gov/articles/slack.html#team-handles)
> Added team handles for Teams Grace and Katherine

- _articles/incident-response-checklist.md
- _articles/secops-incident-response-guide.md
Our ISSM and ISSO have asked to be included in IR emails.  This adds
notes in the relevant IR docs to that effect and I have also updated
the email template with the contact info for our current ISSM and ISSO
role holders.
> Add note to include ISSM and ISSO when sending incident email

- assets/js/analytics-events.js
Related: https://github.com/18F/identity-idp/pull/6063
> Add previous event names to analytics event documentation

- _articles/slack.md
**Why**: As a Login.gov team member, I want to know each of the team Slack handles, so that I can easily get in contact with the team if I need to.
> Add login-ada Slack handle to Slack article

- _articles/appdev-deploy.md
There's some ambiguity in going from one section to the next, so this adds a final step to add a bit of separation and indicate when a deployer is done deploying 🙂
> add final step to appdev deploying handbook page

- _articles/appdev-i18n.md
**Why**: Because the current guidance is outdated, referencing an allowlist file and global function which no longer exist.
h/t @jc-gsa for surfacing
> Update guidance around JS internationalization

- assets/js/private-links.tsx
- assets/js/setup.tsx
- assets/js/typings/@18f/private-eye/index.d.ts
- package-lock.json
- package.json
**Why**: So that we don't need to maintain them ourselves.
Related:
- https://github.com/18F/private-eye/pull/50
- #235
> Bump PrivateEye dependency for first-party type definitions

- _articles/appdev-key-rotation-guide.md
**Why**: It was revealed in our most recent wargames that this guide was absent
> Add a key rotation guide

- _articles/appdev-deploy.md
**Why**:
- To ensure the latest changes are included in the branch cut on Tuesdays. This avoids some confusion for changes perceived to be missing. Since the branch is cut on Tuesday, all changes would be deployed in staging by the time the production deploy happens.
- The changelog script helps reduce the effort of compiling a changelog, and ensures consistency (categories, pull request links, etc).
> Update deploy guide to use latest changes, changelog script

- _articles/appdev-proofing-ruby-worker-jobs.md
- _articles/appdev-risc-ruby-worker-jobs.md
- _articles/github.md
Fixes a few minor issues I noticed while onboarding to Login.gov
> Fix typos/archived repo that I came across while onboarding

- _articles/appdev-deploy.md
**Why**: Because you no longer need to (and cannot) use sudo, so the example command may cause some confusion in its current form.
> Remove sudo from appdev deploy step commands

- _articles/appdev-deploy.md
**Why**: As discussed in the 2022-06-29 Engineering Huddle ([see context](https://docs.google.com/document/d/1g_V2vlT79tScBKIVw7M4UXf15TrG69iUrLHE0yE1GGI/edit#heading=h.hu0pe1h3wlae)).
> Update deploy guide to share release notes in channels

- _articles/slack.md
- _articles/sprint-teams.md
- _data/sprint_teams.yml
This might be a little less accessible to maintain, so I am open to just discarding it, but it seems like the more teams we onboard, the easier it would be to track various fields and make sure they get formatted properly?
> Normalize sprint team data to a .yml file

- _articles/platform-gitlab-env-deploy.md
https://github.com/18F/identity-devops/pull/4956 removed the need for us to duplicate config in chef and tf, so trueing up the docs to match that.
> simplified gitlab env deploy config

- _articles/eng-design-doc.md
- _articles/rfc-template.md
Preserves links as a deprecated archive. I updated the template doc itself with a similar deprecation notice
| | screenshot |
| --- | --- |
| new item | <img width="505" alt="Screen Shot 2022-08-01 at 10 12 47 AM" src="https://user-images.githubusercontent.com/458784/182206432-a4ae0426-30a4-4319-b694-4c5900f25a02.png"> |
| old item | <img width="523" alt="Screen Shot 2022-08-01 at 10 12 57 AM" src="https://user-images.githubusercontent.com/458784/182206435-4bce356a-3c73-47d3-9fe1-7b9cc41c4cc7.png"> |
> Link to RFC template, deprecate Engineering Design template

- _articles/appdev-cloudwatch-dashboard-guide.md
This commit adds a guide on how to create cloudwatch dashboards using the tooling introduced in https://github.com/18F/identity-devops/commit/5e9c2fd9c6fd57524269f7c8c058a3623dadf987
> Add a guide on Cloudwatch dashboards

- _articles/sprint-teams.md
I see in `main/_data/sprint_teams.yml` that we have both a `slack_channel_name` and `slack_channel_url` as variables, but I don't see them on our Sprint Teams page. Maybe that's intentional, but it seems helpful if we point people to this Handbook page?
> Add Slack links to sprint-teams.md

- assets/css/main.scss
- Used when linking to a particular anchor in the handbook
Example
> Add a style for a highlighted target

- _config.yml
- assets/css/main.scss
- package-lock.json
- package.json
Follow-up to TODO item in #308
- Upgrades `identity-style-guide` dependency from `6.3.0` to `6.5.0` to take advantage of latest bug fixes and improvements.
- Imports design system utility methods to avoid hard-coded reference to color value.
- This project [uses the precompiled stylesheet](https://github.com/18F/identity-handbook/blob/dca78d9ed4649c741858bb63a09cb47bb44271e6/_config.yml#L16-L17) shipped through the design system, hence why utility methods are not available by default.
There should be no visual impact by these changes. Test to ensure that the behavior added in #308 continues to work.
> Upgrade, use design system utilities for color reference

- _includes/articles_category.md
- assets/css/main.scss
**Why**: If we have a private google doc that's
findable from the handbook, I want to be able to link to the handbook for where to find that article
Example
- before, you could use Chrome's ["link to snippet"](https://handbook.login.gov/#:~:text=Environment%20Descriptions%0AListing%20of%20environments%20and%20the%20differences%20between%20them%2C%20like%20prod%2C%20pt%2C%20dm%2C%20int%20or%20dev)
- now, you get a little anchor UI element and a specific ID
| ---- | ---- |
|  <img width="660" alt="Screen Shot 2022-09-08 at 3 25 58 PM" src="https://user-images.githubusercontent.com/458784/189236810-9828de03-ccb2-4a1d-9e52-6c834d9a2a2f.png"> | <img width="513" alt="Screen Shot 2022-09-08 at 3 26 17 PM" src="https://user-images.githubusercontent.com/458784/189236828-5c5247db- …
> Add anchors to links to external articles

- _articles/sprint-teams.md
- _data/sprint_teams.yml
**Why**: So that a reader can learn more about the team in the context of reading about each of our teams, and so that someone seeking a Readme has a centralized listing of them.
**Screenshot:**
> Add team Readme documents to Sprint Teams page

- _articles/appdev-deploy.md
- _articles/deploying-sp-to-prod.md
- _articles/slack.md
**Why:** So that the documentation is in sync with our current practices.
- Updates references to deployment days
- Clarifies that deployment is skipped for holidays, since it's more likely now with Monday deploys (e.g. Labor Day)
- Add optional step to use monitoring script for manual inspection
> Update deployment documentation for twice-weekly deployments

- _articles/github.md
- _articles/help-center-contact-form.md
- _articles/reporting-dashboard-architecture.md
- admin/config.yml
- package.json
**Why**: [Federalist is becoming Cloud.gov Pages](https://cloud.gov/pages/federalist-migration/), and as such we'll need to update configurations accordingly.
I'm not sure of any resources for the specifics of these changes ([existing documentation](https://cloud.gov/pages/documentation/getting-started-with-netlify-cms/) still references Federalist), but these were the updates recommended directly from Cloud.gov Pages support folks.
> Update Netlify CMS configuration for Cloud.gov Pages transition

- assets/js/analytics-events.tsx
- assets/js/components/anchor-link.tsx
- assets/js/components/heading.tsx
- assets/js/private-articles.tsx
The dynamic headings in some articles don't play well with the `:target` styling added in #308 
**Note**: This doesn't seem to work on first load, so I'm putting it in draft. I'm not 100% sure why, maybe there's a load ordering or race condition issue somewhere
| --- | --- |
| <img width="758" alt="Screen Shot 2022-09-26 at 1 35 40 PM" src="https://user-images.githubusercontent.com/458784/192375252-733ccb30-01a6-4cd4-b042-5fafa666abd3.png"> | <img width="758" alt="Screen Shot 2022-09-26 at 1 35 32 PM" src="https://user-images.githubusercontent.com/458784/192375268-dbb807fd-e461-4615-bbd3-cce95a1b2d20.png"> |
> Update anchor link headings for dynamic articles

- assets/js/analytics-events.tsx
- assets/js/components/alert.tsx
- assets/js/components/anchor-link.tsx
- assets/js/components/sidenav.tsx
- assets/js/private-articles.tsx
- assets/js/private.tsx
- package-lock.json
- package.json
- tsconfig.json
**Why**: Simplifies implementation and helps align developer experience across projects (already available in IdP, for example).
Specifically, ESBuild v0.14.51 added support for the automatic JSX runtime ([see release notes](https://github.com/evanw/esbuild/releases/tag/v0.14.51)).
> Upgrade ESBuild for JSX automatic runtime support

- _articles/platform-gitlab-env-deploy.md
This documents how we can do terraform-only deploys and limit what ASGs get recycled, as well as talk about how to debug env_runner problems.
> Document gitlab deploy options and how to debug env_runners

- _articles/cloud-gov-pages.md
**Why**: To be able to link as a resource for users seeking access to Netlify CMS, and for other organization managers to help administrate the organization.
**Live preview:** https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/aduth-cloud-gov-pages/articles/cloud-gov-pages.html
> Add "Cloud.gov Pages" article for static site / Netlify CMS access

- _articles/vendor-outage-response-process.md
The actual configs are lowercased: https://github.com/18F/identity-idp/blob/6acbb307b3e37b6f4cf5478223c92016487971d6/lib/identity_config.rb#L287-L288
These configs are case-sensitive so the handbook page was cruising for a bruising
> Fix capitalization typo in vendor outage page

- _articles/queries.md
This is a routine query we do for some service providers to provide a count of total users for their application.
> Service provider linked accounts [LG-8518]

- _articles/appdev-deploy.md
There are a lot of "ifs" in using --skip-migrations which means lots of ways to get cut.   I suggest we pull it from the handbook for now.
> Skip skipping migrations so we do not trip

- assets/js/analytics-events.tsx
Workaround to handle bug fixed by https://github.com/18F/identity-idp/pull/7575
> Update analytics-events page to be handle nullable "types" field

- _articles/queries.md
Based on work I did in https://github.com/18F/identity-idp/pull/7731
> Update queries to include notes about accounts that were deleted

- _articles/devops-scripts.md
Should be reverted whenever https://github.com/18F/identity-devops/pull/5789 is fixed.
> Add bundle exec clarification to bin/scp-s3 instructions

- _articles/incident-response-checklist.md
- _articles/secops-incident-response-guide.md
Based on recent tabletop exercises and refinement of both IR and crisis communications process, this deconflicts the "Comms Lead" role and changes it to something more accurate: "Messenger"
This should be a low risk change for the informal IR role names and prevent confusion.
> WIP - Change Comms Lead role to Messenger and note IR comms threshold criteria

- _articles/sprint-teams.md
- _data/sprint_teams.yml
- assets/css/main.scss
Grays out teams and adds a lil note:
| example |
| --- |
| <img width="658" alt="Screen Shot 2023-02-17 at 11 20 04 AM" src="https://user-images.githubusercontent.com/458784/219767063-d2a01052-17f8-43a9-aac0-b45735b63210.png"> |
> Mark sprint teams that are not active as archived

- _articles/appdev-deploy.md
- _articles/appdev-secrets-configuration.md
- _articles/devops-scripts.md
- _articles/partnerships-test-ssns.md
- _articles/vendor-outage-response-process.md
Adds instructions for using the new passenger restart ssm document. This was swapped in for the asg-recycle command when all that was changing was a value in application.yml. The new ssm document is much faster than our typical environment recycle and doesn't require any scale up/down of instances in an environment. This is [safe to use in production](https://github.com/18F/identity-devops/issues/5651) as it uses the passenger-config restart-app command instead of restarting the entire service, preventing it from dropping connections during the restart.
> Swapping passenger-restart for asg-recycle

- _articles/appdev-deploy.md
Why: As decided in Engineering Huddle 2023-03-15, we'll now be deploying on Tuesdays and Thursdays instead of Mondays and Thursdays.
> Update deployment guide to adjust cadence

- Gemfile
- Gemfile.lock
- Makefile
- _articles/glossary.md
- _articles/openssl-recipes.md
- _articles/piv-ssh.md
- _articles/platform-gitlab.md
- _articles/saml.md
- _articles/secops-incident-response-guide.md
- _articles/toubleshooting-expiring-pivcac.md
- _articles/troubleshooting-pivcacs.md
- _articles/windows-virtual-machine.md
Blocked by #390
Why:
- The native extension fails to compile on my local machine in the older version of html-proofer.
- We should want to update to newer versions of dependencies to take advantages of features and bug fixes.
Note that this is not the latest version of `html-proofer`. There is a 5.x version for the dependency, but it requires Ruby 3.1 or newer, which is currently incompatible with Jekyll and our Cloud.gov Pages build environment.
See upgrade guide: https://github.com/gjtorikian/html-proofer/blob/main/UPGRADING.md
> Upgrade html-proofer to drop nokogumbo dependency

- _plugins/content_typography.rb
Extends existing ContentTypography plugin to apply standard design system styling to "autolinks", which are treated distinctly from Markdown-formatted links.
Copied from https://github.com/18F/identity-dev-docs/pull/319
**Screenshots:**
Example: https://handbook.login.gov/articles/platform-gitlab-env-deploy.html
Before|After
---|---
> Apply design system styling to autolink links

- _articles/vendor-outage-response-process.md
Issue: [LG-8710](https://cm-jira.usa.gov/browse/LG-8710)
We've added a new config flag, `idv_available`, that can be used to disable remote unsupervised identity verification (this augments the existing `vendor_status_*` flags).
This PR updates the vendor outage response process documentation to include a note about this flag. 
(I since I was in there, I also removed references to `partial_outage`--support for this was not implemented.)
> Note new idv_unavailable flag in vendor outage response process

- _articles/onboarding.md
Update the link to Github's docs on gpg keys - the previous link landed on a 404
> Updating onboarding.md

- _articles/glossary.md
Why? It had come up in conversation in discussing our deployed environments, since "ATO" is often a distinguishing factor between them.
> Add "ATO" to glossary

- _articles/github.md
- _config.yml
- _layouts/default.html
- assets/js/setup.ts
- assets/scss/main.css.scss
- package-lock.json
- package.json
Upgrades the Login.gov Design System from v6.5.0 to v7.0.1 (currently beta, but will target stable release prior to merge).
Preview link: https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/aduth-lgds-7/
Compare to live: https://handbook.login.gov/
One difference/regression I notice here that might be worth resolving before the stable release of 7.0.1 is that the handbook's use of the "basic" header lost the vertical centering of the right-hand content in the refactoring of https://github.com/18F/identity-design-system/pull/352 .
> Upgrade Login.gov Design System to v7.0.1

- assets/js/analytics-events.tsx
Scrolling back to the top got annoying and it is not a very good user experience, so I added a "Back to top" link
> Add "Back to top" link with every analytic listing

- _articles/daily-deploy-schedule.md
While watching staging to see a recent feature deploy, I found that the deploy timing didn't match the documentation. In this [conversation in Slack](https://gsa-tts.slack.com/archives/C16RSBG49/p1686596434193659), @mitchellhenke helped me find the current times staging is deployed.
The deeper I dug into it, the more I found a lot of the deploy times were out of date, as were a few links. Not many of them have the same schedule anymore, and the location notating the timing is in a new file now. [The original identity-devops-schedule](https://github.com/18F/identity-terraform/blob/3a37047cfae6949dab1150025c528ccc5332f837/asg_recycle/main.tf#L44-L78) is no longer a valid link and is not where the schedules are kept.
Because of these reasons, I gave the envs their own subheadings.
Other …
> Update deploy timing documentation

- _articles/devops-scripts.md
Adds usage of the `sms-me` command for quickly testing SMS from all US production numbers.
Related PR: https://github.com/18F/identity-devops/pull/6358
> Add note on using sms-me

- _articles/incident-response-checklist.md
- _articles/product-artifacts.md
- _articles/secops-incident-response-guide.md
Updates with an eye toward less redundancy AND less redundancy.
This PR:
* Removes the head-scratchingly-redundant explanation of phases
* Links to the emergency contacts list from both the checklist and guide
* Adds a section referencing the comms team's process
* Adds minimal explanations of the situation room and declare incident workflow
* Bonus - Fixed RFC folder link
> Simplified IR guide

- _articles/platform-gitlab-env-deploy.md
This is so people know what is going on and don't break the format of the file while updating it.
> update docs for the newish allowed_images file format convention

- _articles/appdev-deploy-rotation.md
- _articles/appdev-deploy.md
Updates language to clarify expectations of the deployer, and specifically that the deployer is not directly responsible for any ad hoc patch releases that need to be deployed, but that they should make reasonable accommodations for patch revisions to the routine RC deploy branches.
> Clarify patch deploy ownership and deployer responsibilities

- _articles/appdev-deploy.md
It's a good idea to check if there are extra instances running or if there are issues with the current instances before kicking off a deploy.
> Suggest using ls-servers before deploying

- _articles/appdev-deploy.md
- _articles/vendor-outage-response-process.md
There isn't a specific vendor flag for AAMVA, so direct people to disable IdV completely, and suggest recycling without a migration instance.
This is a followup to an AAMVA outage on August 8, 2023.
See preview of [vendor outage page](https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/sonia-lg-10639-aamva-outage-instructions/articles/vendor-outage-response-process.html) and [appdev deploy page](https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/sonia-lg-10639-aamva-outage-instructions/articles/appdev-deploy.html).
> LG-10639 Mention AAMVA in vendor outage page

- _articles/incident-response-checklist.md
Following [2023-08-09 — AAMVA DLDV down](https://docs.google.com/document/d/1YSJfQkYRJDeIUTbrvdn822r9oIwDhIgX6VVk0dKfDTI/edit), we recognized it might be helpful for the "Messenger" to Slack ping @ login-comms-oncall for their awareness, once a situation is assessed.
> Update incident-response-checklist.md to include ping to comms on-call

- _data/sprint_teams.yml
- spec/sprint_teams_spec.rb
**Why?** To help ensure that expectations of a team are established when new teams are created.
~Blocked by / rebase after / validate against: #463~ (see [before](https://github.com/18F/identity-handbook/pull/464/checks?check_run_id=16145021081))
> Add sprint_teams.yml spec to validate team data

- _articles/appdev-cloudwatch-dashboard-guide.md
- _articles/devops-scripts.md
Add link to devops-wiki article on Cloudwatch dashboards to the handbook article. Add copy-cloudwatch-dashboard script to the Scripts page.
> Extend Cloudwatch dashboard documentation

- _articles/appdev-team-daytime-oncall.md
- _data/sprint_teams.yml
Why?  So that the daytime oncall page reflects the format settled on in an engineering huddle discussion.
Preview [here](https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/em/update-daytime-oncall/articles/appdev-team-daytime-oncall.html).
> add new format for daytime oncall user handles

- _articles/vendor-outage-response-process.md
I give some background on the event, discussing data from Aug 2023. Is that necessary?
Any other dashboards we should point to?
> LG-10735: additional guidance for a resolution proofing result missing alert

- _articles/devops-scripts.md
Related to https://github.com/18F/identity-idp/pull/9510
- Update reinstate-user
- Add confirm-suspend-user
> Update documentation for action-account

- _includes/articles_category.md
Example: https://handbook.login.gov/categories/development.html
| screenshot |
| --- |
| <img width="460" alt="Screenshot 2023-11-09 at 11 30 42 AM" src="https://github.com/18F/identity-handbook/assets/458784/fecb9756-c1be-428f-add0-6901b89e14d5"> |
> Hide "Other Articles" heading if there are no other articles

- _articles/definition-of-done.md
- _articles/definition-of-ready.md
- cspell.json
Team Ada had a ticket to merge [our team-specific Definition of Done document](https://docs.google.com/document/d/1J_-jcXa6DW4n5vLojNu1zAoUGDin0P9St6af0VlDYWE/edit) into the Login-wide one. This PR does that, with a couple other minor cleanup operations on the way. Hopefully not too controversial. I'm happy to split this into more PRs if anyone has concerns.
> Update Definintion of Done and Definition of Ready docs

- _articles/partnerships-test-ssns.md
The instructions stated to use the passenger restart command which we don't want to use anymore. I replaced it with the sandbox recycle command.
> Remove passenger-restart from partnerships-test-ssns.md

- _articles/identity-verification-flow-policy.md
- cspell.json
Documentation for new FlowPolicy, which manages which steps are allowed for an Identity Verification session and user.
Appdev - Architecture - [FlowPolicy page](https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/sonia-flow-policy-documentation/articles/identity-verification-flow-policy.html)
> LG-11797 FlowPolicy documentation

- _articles/manage-50-50-state.md
During deploys, both new and old instances are serving requests. This is called the 50/50 state and requires careful management when changing code that is used across instances.
Appdev - Development - [How to Manage the 50/50 State](https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/sonia-50-50-state/articles/manage-50-50-state.html)
> New article on how to manage the 50/50 state

- _articles/identity-verification-flow-policy.md
Add note about flow_policy_spec additions to FlowPolicy doc. Also remove duplicate paragraph and add a note about extending FlowPolicyHelper.
AppDev - Architecture - [Identity Verification FlowPolicy](https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/sonia-add-spec-note-to-flow-policy-doc/articles/identity-verification-flow-policy.html#flowpolicy-specs)
> Add note about flow_policy_spec additions to FlowPolicy doc

- _articles/vendor-outage-response-process.md
- cspell.json
Login.gov has infrequently been asked to submit transactions to the AAMVA DLDV CERT/Test environment. Add a link to the google doc explaining how to do this to our vendor outage page.
Are there more/better places to link this? Definitely need to also link from the AAMVA outage runbook page that's in progress. @solipet 
Security - Vendor outage response process - [AAMVA DLDV Certificate Testing](https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/sonia-add-aamva-certificate-runbook-link/articles/vendor-outage-response-process.html#aamva-dldv-certificate-testing)
> Add link to AAMVA certificate test process

- _articles/vendor-outage-response-process.md
Add a table of runbooks to individual vendor runbooks, of which only AAMVA has been written.
Security > Vendor outage response process > [Runbooks for individual vendors](https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/dprice-lg-11606-aamva-outage-runbook/articles/vendor-outage-response-process.html#runbooks-for-individual-vendors)
Links to the new [Runbook: AAMVA DLDV outage](https://github.com/18F/identity-devops/wiki/Runbook:-AAMVA-DLDV-outage)
> LG-11606: Add a table of runbooks to individual vendor runbooks

- _articles/vendor-outage-response-process.md
Adds the new Instant Verify runbook to the table of individual vendor runbooks.
Security > Vendor outage response process > [Runbooks for individual vendors](https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/dprice-lg-11868-ln-iv-outage-runbook/articles/vendor-outage-response-process.html#runbooks-for-individual-vendors)
Links to the new [Runbook: LexisNexis Instant Verify outage](https://github.com/18F/identity-devops/wiki/Runbook:-LexisNexis-Instant-Verify-outage)
> LG-11868: add link to LexisNexis Instant Verify outage runbook

- _articles/appdev-deploy.md
Start the sample release branch date with 2024 in the appdev-deploy article to make life a tiny bit easier for deployers until @matthinz's new script is ready to go.
I meant to do this in my last PR and forgot.
> Update the sample release branch date to 2024 in the deploy docs

- _articles/appdev-deploy.md
This adds a small note to clarify that terminating a deploy should usually be followed up with reverting the branch
> Add note about rolling back failed deploys

- _articles/appdev-deploy.md
Removing per request. It is no longer expected that members of this channel would be reviewing the release notes.
> Remove login-ux release notes share from deploy process

- README.md
Title says it all. This is part of the follow up from the [incident review](https://docs.google.com/document/d/1j5ihCdAZUssQN9Y9KevvOEqFcBXU48Iz_66JF9yVE28/edit#heading=h.yjzagco8hnao) for the login.gov brochure outage.
> update README with additional instructions for running locally

- _articles/vendor-outage-response-process.md
[LG-12244](https://cm-jira.usa.gov/browse/LG-12244)
Added a link to the new LexisNexis TrueID outage runbook.
Also added the other possibility for `VENDOR_STATUS_OPTIONS`, [which I found](https://github.com/18F/identity-idp/blob/cf8764c2be19a834c3c7116d35bfccb44de41938/lib/identity_config.rb#L6) in my research for creating the runbook.
I didn't find any behavioral difference between `full_outage` and `partial_outage` in my local testing, though I could've missed something.
> LG-12244: Add link to LexisNexis TrueID outage runbook

- _articles/definition-of-done.md
- _articles/onboarding.md
**What:**
I came across a `design.login.gov` reference while reviewing the definition of done page. 
Removing since it doesn't exist anymore while replacing it with a link to the the LGDS repository.
> Remove design.login.gov reference from DOD

- _articles/platform-gitlab-prod-deploy.md
This updates the deploy docs to add more stuff that we should check, and expand on some other steps.
> update gitlab deploy documentation

- _articles/github.md
Previous spelling "identity-loging" was both mispelled and resulted in a 404 for the link navigation.
> Fix typo for identity-logging repository

- _articles/pull-request-review.md
This makes a few revisions to the [Pull Request Process](https://handbook.login.gov/articles/pull-request-review.html) article to improve the clarity of the language:
- Be very clear about "one approving review" (vs. ambiguous "approval")
- Add note about potential exceptions for others merging a pull request (see [recent example](https://github.com/18F/identity-idp/pull/10184))
- Use full names instead of acronyms ("pull request" instead of "PR", "continuous integration" instead of "CI")
- Capitalize GitHub consistently
This was motivated partly by a recent discussion about our peer review procedure, and whether we have documented expectations around how approval works.
Live preview: https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/gsa-tts/identity-han …
> Clarify language on pull request review

- _articles/pull-request-review.md
This further expands on the clarification to the [Pull Request Process](https://handbook.login.gov/articles/pull-request-review.html) article in #522, adding language that approving review must come from "a member of the engineering team".
Live preview: https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/gsa-tts/identity-handbook/aduth-pr-review-eng/articles/pull-request-review.html
> Clarify pull request approval by engineering

- _articles/appdev-deploy.md
Conventionally, we expect that any recycles to production should be shared in Slack. This is mentioned as part of the regular deployment process, but was not clear as part of a configuration recycle.
> Document announcing in Slack for config recycle

- _articles/appdev-oncall-guide.md
- _articles/troubleshooting-expiring-pivcac.md
- cspell.json
Updates documentation for handling expiring PIV/CAC certificates.
Notably:
- Updates the appdev on-call guide to reference the detailed article for troubleshooting expiring certificates
- Adds a reference to [notifications for Federal PKI ecosystem changes](https://www.idmanagement.gov/fpki/notifications/#notifications), which often include postings informing about an upcoming replacement certificate
- For example, a certificate expiring at the time of writing ["Lockheed Martin Root Certification Authority 6"](https://github.com/18F/identity-pki/blob/main/config/certs/C%3DUS%2C%20ST%3DColorado%2C%20L%3DDenver%2C%20O%3DLockheed%20Martin%20Corporation%2C%20OU%3DCertification%20Authority%2C%20CN%3DLockheed%20Martin%20Root%20Certification%20Authority%206.pem) has a related posting advising …
> Improve documentation for handling expiring PIV/CAC certificates

- _articles/manage-50-50-state.md
Following up on: https://github.com/18F/identity-idp/pull/10429#issuecomment-2056885629
> Add additional details about dropping columns to 50-50 state documentation

- _articles/github-gitlab.md
> Mark more repositories as having moved to GitLab

- _articles/appdev-secrets-configuration.md
Currently the page regarding [Secrets and Configuration](https://handbook.login.gov/articles/appdev-secrets-configuration.html) includes language implying that updates can be made by editing the secrets file in s3 by downloading, editing, and uploading. This is not recommended, users should use the `app-s3-secret` script to make edits. So this PR removes that language.
[Conversation in Slack regarding this change](https://gsa.enterprise.slack.com/archives/C16RSBG49/p1715694023104519)
> Remove text stating updates can be made by whatever means necessary

- _articles/slack.md
- Rename few channels
- Remove a few archived channels
- Update URLs to new enterprise domain
- Hide inactive sprint team channels
> Update Slack channels page

- _articles/queries.md
- _articles/sql-style-guide.md
Starts a small SQL style guide! Like it says inside, it's not enforced, but I would like to start norming as a team on these!
I found that [Gitlab has a style guide](https://handbook.gitlab.com/handbook/business-technology/data-team/platform/sql-style-guide/) which I skimmed for reference.
I would like to find a way to use an automated tool like [sqlfluff](https://github.com/sqlfluff/sqlfluff) that they mention, but currently, it would not work for our codebases that have SQL embedded inside ruby files. I've got some ideas for how we can cobble something togethe.
> Add a SQL style guide

- _articles/saml.md
The process for getting the certificate was a little too vague to follow.
I updated this to indicate that there are different processes for the hosted and local apps.
I also can't tell you why the local process is that way, but that's the only way I've been able to get a valid fingerprint. I'd love to have someone explain this.
> Update SAML Fingerprint process

- _articles/appdev-feature-flags.md
- _articles/appdev-secrets-configuration.md
Adds a new article describing the purpose and lifecycle of feature flags in Rails applications.
This was an action item from the 2024-05-29 Engineering Huddle meeting.
1. Go to https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/gsa-tts/identity-handbook/aduth-feature-flags/articles/appdev-feature-flags.html
2. Verify that the content includes everything you'd expect to learn about how we use feature flags, as if you were a new developer to the team
> Add Feature Flags article

- _articles/devops-scripts.md
- spec/html_spec.rb
- spec/support/matchers.rb
If copy-pasted some of these commands would error because the missing `\` means that it was two separate commands
Copy-pasting these commands works! Requires less thingking
Another option would be to one-line all of these (but that means more horizontal scrolling)
> Add \ to escape newlines for multi-line bash commands

- _articles/github-gitlab.md
This is making me think we need a more linear "engineering onboarding" and document, but for the the time being, I want to make sure we note this somewhere at least
> Add documentation on signed commits for GSA-TTS repositories

- _articles/logs-schema.md
- cspell.json
This PR is to address duplicate heading being displayed on the Handbook page.
> LG-13596: Changes to remove duplicate heading in logs schema for redshift page

- _articles/appdev-risc-ruby-worker-jobs.md
> Remove instruction to set risc_notifications_active_job_enabled

- _articles/incident-review-template.md
- _articles/product-artifacts.md
**Why**: We have moved away from the term postmortem
> Rename postmortem template to incident review template

- _articles/logs-schema.md
This PR resolves the schema changes for production Redshift tables and resolve a bug introduced in [LG-13596](https://cm-jira.usa.gov/browse/LG-13596)
> LG-13778: Changes to address the schema changes and resolve a bug

- _articles/cloudwatch-101.md
Added instructions for logging in via AWS directly, since that's easier if you know you need to switch roles.
> Add cloudwatch query instructions to log in via the UX

- _articles/queries.md
- Recurring request, documenting for easier discovery instead of searching Slack
> Add query for cumulative unique active idv accounts (LG-14000)

- _articles/cloud-gov-pages.md
Being able to manage static sites either via Cloud.gov Pages or Netlify CMS requires additional permissions to the GSA-TTS GitHub organization. This is a common source of confusion.
The goal of this pull request is to add additional text to the Cloud..gov Pages handbook article to explain this prerequisite, and link to existing guidance on requesting access to be added to the relevant GitHub teams.
> Add GSA-TTS prerequisite to Cloud.gov Pages access

- _articles/cloud-gov-pages.md
Updates Cloud.gov Pages article to use the `{% link %}` helper to generate a URL to the GitHub article, so that it works correctly in local and preview environments.
Addresses https://github.com/GSA-TTS/identity-handbook/pull/613#discussion_r1811092839
**Testing Instructions:**
1. Go to https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/gsa-tts/identity-handbook/aduth-cloud-gov-link-helper/articles/cloud-gov-pages.html
2. Take note of the URL hostname in your address bar
3. Click "request access to be added"
4. Observe that you're still on the same URL hostname from Step 2
> Use link helper to generate GitHub article URL

- _articles/appdev-deploy.md
Following a discussion on the potential understanding of "When to deploy" / "When to not deploy" as more binding than originally intended. I added a few changes and restructured this part to hopefully make it clearer that we have a regular schedule for deployments, that we can deploy at other times, and there are times we may consider not deploying due to less time and people being available if something goes wrong.
> Change language around deploy cadence

- _articles/appdev-deploy.md
The [bin/tag-release](https://gitlab.login.gov/lg/identity-pki/-/blob/fb7b99db26a5c518709123e76c056bdfe610226d/bin/tag-release#L7) script includes setting this environment variable, so we can remove it here
```
#!/bin/sh
set -e
set -x
TAG=$(date -u +"%Y-%m-%dT%H%M%S")
GPG_TTY=$(tty) git tag -s $TAG -m "$TAG release"
git push origin $TAG
```
> Remove GPG_TTY system variable from tag-release documentation

- index.md
Updates the handbook's homepage title from "Login Handbook" to "Login.gov Handbook".
Our organization is not called "Login", so our handbook should reflect who we are.
Verify title (both `<h1>` and `<title>`) show "Login.gov Handbook", not "Login Handbook".
Before|After
---|---
> Rename handbook title "Login.gov Handbook"

- _layouts/default.html
Fixes an issue where clicking the logo in a Cloud.gov Pages preview environment results in a 404.
Cloud.gov Pages are served from subdirectories, so hard-coding `"/"` will always result in a 404 in these environments, and should be prepended with `{{ site.baseurl }}`.
Related resource: https://mademistakes.com/mastering-jekyll/site-url-baseurl/
1. Go to preview site for this branch
2. Click logo
3. Observe that you're directed to the homepage of the handbook
> Fix logo homepage link in Cloud.gov Pages preview

- Gemfile
- Gemfile.lock
- _components/alert_component.html.erb
- _components/alert_component.rb
- _components/base_component.rb
- _components/breadcrumb_component.rb
- _plugins/view_component.rb
- index.md
Updates the homepage to include a visually-distinct link to the internal handbook.
Currently, it's hard to know that an internal handbook even exists with additional handbook material. The intent here is to improve awareness of its existence, without being too overly distracting.
Related Slack discussion: https://gsa-tts.slack.com/archives/CEUQ9FXNJ/p1733941222366069
1. Go to preview URL
2. See alert with link to internal handbook
3. Verify that the link is functional
Before|After
---|---
> Add link to internal handbook in homepage intro

- _components/breadcrumb_component.html.erb
- _components/breadcrumb_component.rb
- _layouts/article.html
Adjusts visual appearance of breadcrumbs added in #628 to remove inherent padding from the component.
This is to tighten up spacing and remove awkward offset of beginning of page content relative to the sidebar.
1. Go to preview URL
2. Click on article or category
3. See that sidebar top matches content top
Before|After
---|---
> Remove inherent padding from breadcrumb

- index.md
Updates the introduction text of the handbook to be collapsed to a single paragraph, so that people can quickly get to the good stuff.
1. Go to preview URL
2. Observe less scrolling effort to get to articles
Before|After
---|---
> Collapse introductory paragraphs on homepage

- _categories/development.md
- _categories/partnerships.md
- _categories/platform.md
- _categories/private.md
- _categories/product.md
- _categories/reporting.md
- _categories/security.md
- assets/scss/main.css.scss
- index.md
Updates the display of handbook categories:
- Ensures description for each
- Reduce by one row / avoid odd-number items (remove "Private articles" in favor of #640)
- Visual refinements: Reduce spacing between rows to match columns, align heading icon
1. Visit preview URL
2. Observe list of categories meets criteria listed above
Before|After
---|---
> Refine categories listing appearance and descriptions

- _layouts/category.html
Quick follow-up to #642, applies padding changes to Categories layout as well, missed in that pull request.
Repeat Testing Plan from #642
Before|After
---|---
> Remove inherent padding from breadcrumb (2)

- spec/plugins/view_component_spec.rb
Adds some basic test coverage for the Jekyll + view_component plugin added in #628 and iterated in subsequent pull requests.
```
rspec spec/plugins/view_component_spec.rb 
```
> Add test coverage for ViewComponent plugin

- _config.yml
Adds additional files to be excluded from built site which are relevant for development and build, but not for the published site:
- `cspell.json` (spell-checking in CI)
- `federalist.json` (used by Cloud.gov Pages during build)
- `spec` (tests run in CI)
- `tsconfig.json` (TypeScript configuration for JavaScript source files)
Also sorts the list.
Verify that `_site` contains only files that should be published to the live site:
```
rm -rf _site && bundle exec jekyll build
```
> Exclude additional files irrelevant for published site

- Gemfile
- Gemfile.lock
- _config.yml
Removes unused `jekyll-environment-variables` gem.
Last reference removed in #541
Verify no code references to `site.env`
> Remove unused jekyll-environment-variables gem

- _articles/types-of-documentation.md
- assets/scss/main.css.scss
Adds a new article "Types of Documentation"
At our recent Handbook Documentation Club meeting, we discussed the "what and where" of our different types of documentation. This article exists to capture this in a way that can be shared with others to help explain where they can expect to find (or author) some type of documentation.
Usually, this comes down to:
- What is the content about and who is it for
- What is the authoring experience
- Technical expertise requirements (Git, Markdown vs. WYSIWYG)
- Approvals process
And to a lesser extent:
- How up-to-date is the content?
- How is it structured? (and discoverability more broadly)
Review the new article content for accuracy and readability.
Preview URL: https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview …
> Add "Types of Documentation" article

- _articles/identity-verification-flow-policy.md
The Identity Verification FlowPolicy page previously linked to a mural.  It now links to a figma.
Check that the new link works.
> Update out of date link for idv_session changes

- _articles/cloudwatch-101.md
Updates the ["CloudWatch 101" article section on `count_distinct`](https://handbook.login.gov/articles/cloudwatch-101.html#count_distinct) to include two more options for querying unique values (`new_event`, multiple `stats` aggregation).
Related Slack discussion: https://gsa-tts.slack.com/archives/C01710KMYUB/p1740147681093639
Verify readability and accuracy of the documented alternative suggestions to `count_distinct`.
Live preview: https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/gsa-tts/identity-handbook/aduth-cloudwatch-uniqueness/articles/cloudwatch-101.html#count_distinct
> Document additional options for CloudWatch uniqueness

- _articles/partnerships-advisory-group.md
- _articles/partnerships-contact-us-webpage.md
- _articles/partnerships-dashboard.md
- _articles/partnerships-external-slack.md
- _articles/partnerships-guides-faqs.md
- _articles/partnerships-help-center.md
- _articles/partnerships-internal-slack.md
- _articles/partnerships-market-segments.md
- _articles/partnerships-newsletter.md
- _articles/partnerships-organizational-structure.md
- _articles/partnerships-press-kit.md
- _articles/partnerships-program-roadmap.md
- _articles/partnerships-program-updates.md
- _articles/partnerships-webinar.md
- _articles/partnerships-zendesk.md
- assets/js/setup.ts
Ticket: [!165](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/165)
The Outreach team has drafted content and new pages to add documentation for the Partnerships team, and this PR implements it.
> Add new content for partnerships page

- _articles/appdev-deploy.md
Based on discussion in the [2025-06-18](https://docs.google.com/document/d/1g_V2vlT79tScBKIVw7M4UXf15TrG69iUrLHE0yE1GGI/edit?tab=t.0#heading=h.s3svy7wb0by6) engineering huddle, the manual testing has gotten more burdensome and less valuable. We have metrics and alerts that should notify us if something is going wrong. The identity verification team also currently does regular manual testing of the document verification step so part of this work is duplicative.
> Remove manual testing from deploy process

- _articles/vendor-outage-response-process.md
Adds a link to the `DoS Passport API outage` runbook
> LG-16339: Update vendor-outage-response-process.md
